# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_foruser', '0002_auto_20171206_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='vale',
        ),
        migrations.AddField(
            model_name='option',
            name='value',
            field=models.IntegerField(default=8, verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=32, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tp',
            field=models.IntegerField(choices=[(1, '打分'), (2, '单选'), (3, '评价')]),
        ),
    ]
